{% set version = "3.3.5" %}

package:
  name: fftw-mpi
  version: {{ version }}

source:
  fn: fftw-{{ version }}.tar.gz                                             # [not win]
  url: http://www.fftw.org/fftw-{{ version }}.tar.gz                        # [not win]
  sha256: 8ecfe1b04732ec3f5b7d279fdb8efcad536d555f9d1e8fabd027037d45ea8bcf  # [not win]
  fn: fftw-{{ version }}-dll32.zip                               # [win32]
  url: ftp://ftp.fftw.org/pub/fftw/fftw-{{ version }}-dll32.zip  # [win32]
  fn: fftw-{{ version }}-dll64.zip                               # [win64]
  url: ftp://ftp.fftw.org/pub/fftw/fftw-{{ version }}-dll64.zip  # [win64]

build:
  number: 1

requirements:
  build:
    - perl 5.22.2.1
    - openmpi  # [not win]

  run:
    - openmpi  # [not win]

test:
  commands:
    - exit $(test -f ${PREFIX}/lib/libfftw3f.a)          # [not win]
    - exit $(test -f ${PREFIX}/lib/libfftw3.a)           # [not win]
    - exit $(test -f ${PREFIX}/lib/libfftw3l.a)          # [not win]
    - exit $(test -f ${PREFIX}/lib/libfftw3f_threads.a)  # [not win]
    - exit $(test -f ${PREFIX}/lib/libfftw3_threads.a)   # [not win]
    - exit $(test -f ${PREFIX}/lib/libfftw3l_threads.a)  # [not win]

    # Verify headers are installed
    - test -f ${PREFIX}/include/fftw3.h                  # [not win]
    - test -f ${PREFIX}/include/fftw3-mpi.h              # [not win]
    - if not exist %LIBRARY_INC%\\fftw3.h exit 1         # [win]

    # Verify shared libraries are installed
    {% set fftw_libs = [
            "libfftw3",
            "libfftw3_threads",
            "libfftw3f",
            "libfftw3f_threads",
            "libfftw3l",
            "libfftw3l_threads",
            "libfftw3_mpi",
            "libfftw3f_mpi",
            "libfftw3l_mpi",
    ] %}

    {% for lib in fftw_libs %}
    - test -f ${PREFIX}/lib/{{ lib }}.dylib    # [osx]
    - test -f ${PREFIX}/lib/{{ lib }}.so       # [linux]
    {% endfor %}
      
    {% set baselist = ["libfftw3f-3", "libfftw3-3", "libfftw3l-3"] %}
              
    {% for base in baselist %}          
    - if not exist %LIBRARY_LIB%\\{{ base }}.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\{{ base }}.dll exit 1  # [win]          
    {% endfor %}

about:
  home: http://fftw.org
  license: GPL 2
  summary: "The fastest Fourier transform in the west."
