travis:
  secure:
    BINSTAR_TOKEN: Xg3txD8jDvjaImDpknGFrBTUMgyvNC8qW0doMHaxt1kSoRXywsipgsIu+PyOKXa4jqvU4E86Gv0r07WYX/L0JiP+kCLRp3hYiP+xJOvEitcGBKygLkuKAt99xHuDUGB0heWDEhWYGDlh5jNMWj1OtDf+8bXiSqYL8XUrLwM1/QPqysdYZCnrzIOcz4mh5p671RKP93GSTOmIna2d+vFHWHdG4UgCSZLM40oDgLP3rqzA1KnpZD623GIALuzP1osBKQRlSg0vSNL3k5LOILkqUZE+dIebjUI2NLdYb7PKBUjyEr5nhuARV/6briA6lssKMo81ViAzxtEqxD9KdQ4RcaJ3mpwrc1+gnmEMPlTotSUqGttB/FAKMzXtT5LkIPuuwNAHj1tme3TotnRlei6pVplC2XHfzJPJGI/qmLf8fa0L6GfoGslB2grlzYiAL3TPpdYd4D4RqSspH8mMnRBafUGoA/x8GPfctBEoLZN4rUhcqDj+9m3msNE18ck/a3UrVhKITvkJFXTtIj4B/3zvRMLg7QiUU/KfcCxHN9a55f9xZH9Q1AX9E9UwS5RNvSx8GhviiETDYq7myy8YVtWYsIeWRL+s2Y2Hdu5gzsbHgX97c83I9d8hnMQ17looiw7ywfq/ypPyKTp2gSCr6TWPTdH9wCiBX+ADexD9ObpfOSU=
appveyor:
  secure:
    BINSTAR_TOKEN: OcAUZlpSDgQtX8QAIX7qr8iZhsrOWwlmuyDECE7wAYBRlvXIBJ7BbXhX/Fmz4Oib

channels:
  sources: [cryoem, defaults, conda-forge]
  targets:
  - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: fftw-mpi-feedstock

provider:
  linux: circle
  osx: travis
  win: appveyor

azure:
  build_id: blank
